apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Signal Sciences container with SigSci Agent and Module for Apache2
  labels:
    app: sigsci-apache-ubuntu1604
    version: 1.14.4-1.4.6
  name: sigsci-apache-ubuntu1604
  namespace: default
spec:
  ports:
  - name: tcp-80-80-7i2jr
    port: 80
  selector:
    app: sigsci-apache-ubuntu1604
    version: 1.14.4-1.4.6
  type: LoadBalancer
